name: Fyx Autodoc
description: An automated method to generate in-code api skeletons
inputs:
  type:
    description: "Operation selection"
    required: true
branding:
  icon: 'archive'
  color: 'blue'
runs:
  using: 'docker'
  image: 'Dockerfile'
