name: Testing Fyx-Autodoc
on:
  push:
  workflow_dispatch:

jobs:
  global:
    name: Global tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
      - name: Fyx Testing
        uses: PharaohCola13/fyx-autodocumentation@main
        env:
          fyx_username: PharaohCola13
          fyx_email: academic@sriley.dev
