name: Update Fyx-Autodoc 
on: [workflow_dispatch]
      
jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
       ref: main
    - name: Login to GHCR
      run: |
        echo $CR_PAT | docker login ghcr.io -u PharaohCola13 --password-stdin
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Publish 
      run: |
        docker build . --tag ghcr.io/pharaohcola13/fyx-autoapi:latest
        docker push ghcr.io/pharaohcola13/fyx-autoapi:latest
