name: Testing Fyx-Autodoc
on: [workflow_dispatch]

jobs:
  global:
    name: Sample testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout testing branch
        uses: actions/checkout@master
        with:
          ref: test
      - name: Fyx Testing
        uses: PharaohCola13/fyx-autodoc@main
        with:
          dir: ./
          type: all
        env:
          FYX_USERNAME: PharaohCola13
          FYX_EMAIL: academic@sriley.dev
      - name: Show results
        run: |
          cat ${{github.workspace}}/test.py
          cat ${{github.workspace}}/test.r
          cat ${{github.workspace}}/test.rs
          cat ${{github.workspace}}/api-reference.rst
          
          
