name: Testing Fyx-Autodoc
on: [workflow_dispatch]

jobs:
  global:
    name: Sample testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout testing branch
        uses: actions/checkout@master
        with:
          ref: test
      - name: Fyx Testing
        uses: PharaohCola13/fyx-autodoc@main
        with:
          dir: ./
          type: all
        env:
          FYX_USERNAME: PharaohCola13
          FYX_EMAIL: academic@sriley.dev
      - name: Show results
        run: |
          cat ${{github.workspace}}/test.py
          cat ${{github.workspace}}/test.r
          cat ${{github.workspace}}/test.rs
          cat ${{github.workspace}}/api-reference.rst
      - name: stage changed files
        run: git add ${{github.workspace}}/*
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Sample tests for fyx-autoapi" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

