name: Testing Fyx-Autodoc
on: [workflow_dispatch]

jobs:
  global:
    name: Global tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout testing branch
        uses: actions/checkout@master
        with:
          ref: test
      - name: Fyx Testing
        uses: PharaohCola13/fyx-autodocumentation@main
      - name: Show results
        run: |
          cat ${{github.workspace}}/test.py
